### ISSUE TITLE
On death items despawn too quickly

### ISSUE THREAD

**Issue by FlooferDoofer** [ArchitectSMP/mc-config#102]
Some players have been reporting items despawning very quickly, even within second.
One players died next to their bed, respawned and their stuff was already gone.
I have heard multiple players complaining about it, but they were usually further away and they could have just arrived too late.
But this one player let us know right away. No server issues at any of the reported moments.

**Comment by bloodycoffin** [comment]
Which player? @FlooferDoofer

**Comment by bloodycoffin** [comment]
spigot.yml sets "item-despawn-rate: 6000" at 5 minutes, if the player did not immediately press respawn then I believe it counts towards the despawn rate while you stay in the death view which means your items will be gone.
Maybe I can tell something with co lookup or what ever but as long as it is only one person we cannot assume that it is a bug.

**Comment by bloodycoffin** [comment]
just FYI paper.yml does have an override for the item-despawn-rate but only when enabled and for specific items (to have for example stone and cobblestone despawn faster)
    alt-item-despawn-rate:
      enabled: false
      items:
        COBBLESTONE: 300
        
But right now we are not using that

**Comment by bloodycoffin** [comment]
There is a bug open with Mojang https://bugs.mojang.com/browse/MC-117783 but not sure if they're actively looking at fixing it

**Comment by bloodycoffin** [comment]
Investigated, does not seem to be an overall problem and reported players seemingly too late to retrieve gear
